### ISSUE TITLE
CRUD Pegawai

### ISSUE THREAD

**Issue by nabilsaragih** [nabilsaragih/PA_APL#3]

**Comment by MaulanaASetiawan** [comment]
terus ni gimana bang?

**Comment by nabilsaragih** [comment]
ini kayak to do doang

**Comment by MaulanaASetiawan** [comment]
hoo ok nanti dicommitnya tetep sama kek kemaren?

**Comment by nabilsaragih** [comment]
yang mau ngerjakan issuenya nanti ku assign issuenya

**Comment by MaulanaASetiawan** [comment]
aku nyoba ngerjain yang pegawai dulu ni

**Comment by nabilsaragih** [comment]
iya tetap sama, kalau udah commit ku close issuenya

**Comment by nabilsaragih** [comment]
ku assign ke kamu ya

**Comment by MaulanaASetiawan** [comment]
ok, ingpo ini masukkan datanya ke csv tu langsung atau dibuat tombol? contohnya kek, tambah data dlu baru nanti ada menu yg buat si data dimasukkan sekaligus
jadi nda langsung masuk csv

**Comment by nabilsaragih** [comment]
langsung aja gus
